name: FER App Deploy

on:
    push:
        branches:
        - main
        paths:
          - svelte_client/**
          - server.py
          - requirements.txt
          - predict.py
          - .github/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Configure NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Check Front-end build
      run: |
        cd svelte_client
        npm install
        npm run build

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd Facial-Emotion-Recognition
          git pull origin main
          
          # Install Python dependencies
          conda activate fer_env
          python -m pip install -r requirements.txt
          
          # Build front-end
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd svelte_client
          npm install
          npm run build
          
          # restart web server
          sudo /bin/systemctl restart fer_app.socket nginx
